import type { AuthUser } from './roles';

export type DemoAccount = AuthUser & {
  password: string;
};

export const demoAccounts: DemoAccount[] = [
  {
    id: 'demo-super-admin',
    name: 'Sonal Super Admin',
    email: 'superadmin@spms.local',
    password: 'SuperAdmin@123',
    role: 'SUPER_ADMIN',
    status: 'ACTIVE',
    mobile: '+91 90000 10001',
    department: 'Executive',
    designation: 'Super Admin',
    reportingManager: 'Board',
  },
  {
    id: 'demo-admin',
    name: 'SPMS Admin',
    email: 'admin@spms.local',
    password: 'Admin@123',
    role: 'ADMIN',
    status: 'ACTIVE',
    mobile: '+91 90000 10002',
    department: 'Operations',
    designation: 'Platform Admin',
    reportingManager: 'Sonal Super Admin',
  },
  {
    id: 'demo-hr',
    name: 'Hema HR',
    email: 'hr@spms.local',
    password: 'HR@123',
    role: 'HR',
    status: 'ACTIVE',
    mobile: '+91 90000 10003',
    department: 'Human Resources',
    designation: 'HR Executive',
    reportingManager: 'SPMS Admin',
  },
  {
    id: 'demo-manager',
    name: 'Maya Manager',
    email: 'manager@spms.local',
    password: 'Manager@123',
    role: 'MANAGER_TEAM_LEAD',
    status: 'ACTIVE',
    mobile: '+91 90000 10004',
    department: 'Engineering',
    designation: 'Team Lead',
    reportingManager: 'SPMS Admin',
  },
  {
    id: 'demo-employee',
    name: 'Esha Employee',
    email: 'employee@spms.local',
    password: 'Employee@123',
    role: 'EMPLOYEE',
    status: 'ACTIVE',
    mobile: '+91 90000 10005',
    department: 'Engineering',
    designation: 'Software Engineer',
    reportingManager: 'Maya Manager',
  },
  {
    id: 'demo-sales-crm',
    name: 'Sameer Sales',
    email: 'sales@spms.local',
    password: 'Sales@123',
    role: 'SALES_CRM',
    status: 'ACTIVE',
    mobile: '+91 90000 10006',
    department: 'Sales',
    designation: 'CRM Specialist',
    reportingManager: 'SPMS Admin',
  },
];
